name: ha-bridge

services:
  ha-bridge:
    image: crpi-w1apw3w3zzp43y80.cn-shanghai.personal.cr.aliyuncs.com/weidaye1122/ha_bridge:latest
    container_name: ha-bridge
    user: root
    restart: unless-stopped
    ports:
      - "18080:18080"
    environment:
      APP_PORT: 18080
    volumes:
      - ha-bridge-data:/data
      - ha-bridge-secrets:/run/secrets

volumes:
  ha-bridge-data:
  ha-bridge-secrets: